# NOTE: CONFIG_PATH must be set to this file to run the application.

# Для запуска приложения укажите переменную окружения CONFIG_PATH с этим файлом:

# PowerShell: $env:CONFIG_PATH="D:/GOLANG/url-shortener/config/local.yaml"
# CMD:        set CONFIG_PATH=D:/GOLANG/url-shortener/config/local.yaml
# Bash:       export CONFIG_PATH=D:/GOLANG/url-shortener/config/local.yaml

env: "local" # local, dev, prod
storage_path: "D:/GOLANG/url-shortener/storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s